# Generated by Django 2.2.3 on 2019-08-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='collage',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('c_name', models.CharField(max_length=50)),
                ('u_id', models.ForeignKey(on_delete='on_delete', to='test1.university')),
            ],
            options={
                'db_table': 'collage',
            },
        ),
    ]
