# Generated by Django 2.2.3 on 2019-08-02 22:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('test1', '0002_collage'),
    ]

    operations = [
        migrations.CreateModel(
            name='u_profile',
            fields=[
                ('u_p_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.IntegerField(max_length=10)),
                ('c_id', models.ForeignKey(on_delete='on_delete', to='test1.collage')),
                ('u_id', models.ForeignKey(on_delete='on_delete', to='test1.university')),
                ('user', models.ForeignKey(on_delete='on_delete', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'u_profile',
            },
        ),
    ]
