# Generated by Django 2.2.3 on 2019-08-05 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_auto_20190805_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='date',
            field=models.DateField(),
        ),
    ]
