# Generated by Django 2.2.3 on 2019-08-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0006_auto_20190805_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='date',
            field=models.DateField(),
        ),
    ]
