# Generated by Django 2.2.3 on 2019-08-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_auto_20190806_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
