# Generated by Django 2.2.3 on 2019-08-06 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0008_auto_20190806_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weather_data',
            old_name='date',
            new_name='DATE',
        ),
    ]
