# Generated by Django 2.2.3 on 2019-09-06 18:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0009_auto_20190806_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather_data',
            name='sdt',
            field=models.DateField(default=datetime.datetime(2019, 9, 6, 23, 30, 57, 649615)),
        ),
        migrations.AlterField(
            model_name='u_profile',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='weather_data',
            name='DATE',
            field=models.DateField(),
        ),
    ]
