# Generated by Django 2.2.3 on 2019-09-06 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0010_auto_20190906_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather_data',
            name='sdt',
        ),
    ]
