# Generated by Django 2.2.3 on 2019-09-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0011_remove_weather_data_sdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='DATE',
            field=models.DateTimeField(),
        ),
    ]
