# Generated by Django 2.2.3 on 2019-09-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_auto_20190912_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather_data',
            name='DATE',
            field=models.DateField(),
        ),
    ]
